version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
