name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-3
      ECR_BACKEND: 122610518396.dkr.ecr.eu-west-3.amazonaws.com/backend
      ECR_FRONTEND: 122610518396.dkr.ecr.eu-west-3.amazonaws.com/frontend

    steps:
      - name: Debug workspace
        run: ls -R

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION |
            docker login --username AWS --password-stdin $ECR_BACKEND
          aws ecr get-login-password --region $AWS_REGION |
            docker login --username AWS --password-stdin $ECR_FRONTEND

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: List files in workspace
        run: ls -R

      - name: Build and Push Backend Image
        run: |
          if [ ! -d "backend" ]; then
            echo "Error: Directory backend does not exist.";
            exit 1;
          fi
          docker build -t backend:latest -f backend/Dockerfile backend
          docker tag backend:latest $ECR_BACKEND:latest
          docker push $ECR_BACKEND:latest

      - name: Build and Push Frontend Image
        run: |
          if [ ! -d "frontend" ]; then
            echo "Error: Directory frontend does not exist.";
            exit 1;
          fi
          docker build -t frontend:latest -f frontend/Dockerfile frontend
          docker tag frontend:latest $ECR_FRONTEND:latest
          docker push $ECR_FRONTEND:latest

      - name: Terraform Init and Apply
        working-directory: projet-aws-devops/infra
        run: |
          terraform init -input=false
          terraform apply -auto-approve \
            -var="db_username=${{ secrets.DB_USERNAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}"